### ISSUE TITLE
Live push does not restart `main` service when using single Dockerfile

### ISSUE THREAD

**Issue by chrisys** [balena-io-modules/livepush#83] opened 2020-08-31 13:52 UTC
I've been working with a single container project and found that after the initial push, further changes are detected but the container is not restarted. I'm able to reproduce this on `raspberrypi3-2.53.9+rev1-dev-v11.9.9` by using something very simple such as [balena-idling](https://github.com/balena-io-playground/balena-idling).

To reproduce, put the device into local mode, push the project, all should work fine. Make a simple change to the Dockerfile, e.g. change `Idling...` to `Idler...`, the container is built and the service exits, but the new one does not start. See below screenshot.

![Screenshot 2020-08-31 at 14 52 21](https://user-images.githubusercontent.com/521698/91727398-93c66d80-eb99-11ea-96dc-097c8d0ad05d.png)

I have also observed that the existing container does not always exit, sometimes it stops at the line above. If you make another change to the Dockerfile, the change is detected but it doesn't commence the build and hangs on `Cancelling ongoing rebuild for service main` and does not proceed.

**Comment by chrisys** [comment] 2020-08-31 14:02
A followup; if you leave it for some time you get a couple more messages:

![Screenshot 2020-08-31 at 15 01 39](https://user-images.githubusercontent.com/521698/91728374-e8b6b380-eb9a-11ea-83d2-2a4fd806a79c.png)

**Comment by pdcastro** [comment] 2020-08-31 22:32
I believe I was able to reproduce this issue - or something quite similar - on balenaOS 2.53.9 with supervisor v11.9.9 on a Raspberry Pi 3 device. Looking at the `journalctl -au resin-supervisor` output, the root cause would be this supervisor bug: https://github.com/balena-io/balena-supervisor/issues/1450 (An unhandled exception that causes the supervisor to become partially unresponsive, and the CLI / livepush to timeout or issue "socket hang up" errors.)

Updating the supervisor from v11.9.9 to v11.12.4 appeared to fix it - though again, testing was limited (tried changing the Dockerfile some 10 times with each supervisor version).

**Comment by chrisys** [comment] 2020-09-01 08:23
Thanks for testing @pdcastro - I confirm it's working OK when using v11.12.4.

**Comment by srlowe** [comment] 2020-09-14 11:45
@chrisys Closing this issue, since it seems resolved now (please let me know if you think more investigation is needed).

**Closed by srlowe** 2020-09-14 11:45 UTC
